/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectw;

/**
 *
 * @author Admin
 */
public class membersOfProject extends javax.swing.JFrame {

    /**
     * Creates new form membersOfProject
     */
    public membersOfProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search_setitle3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search_setitle11 = new javax.swing.JLabel();
        search_setitle8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search_setitle9 = new javax.swing.JLabel();
        search_setitle4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search_setitle10 = new javax.swing.JLabel();
        search_setitle6 = new javax.swing.JLabel();
        exit_main2 = new javax.swing.JButton();
        exit_main3 = new javax.swing.JButton();
        Front = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        search_setitle3.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        search_setitle3.setForeground(new java.awt.Color(255, 255, 0));
        search_setitle3.setText("GROUP  MEMBERS");
        jPanel1.add(search_setitle3);
        search_setitle3.setBounds(50, 30, 520, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/zehsan.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 130, 110);

        search_setitle11.setFont(new java.awt.Font("MRT_Naskhi", 3, 24)); // NOI18N
        search_setitle11.setForeground(new java.awt.Color(255, 255, 0));
        search_setitle11.setText("Name        : Ehsanullah");
        jPanel1.add(search_setitle11);
        search_setitle11.setBounds(220, 160, 280, 40);

        search_setitle8.setFont(new java.awt.Font("MRT_Naskhi", 3, 24)); // NOI18N
        search_setitle8.setForeground(new java.awt.Color(255, 255, 0));
        search_setitle8.setText("Reg No.# : FA17-BSE-024");
        jPanel1.add(search_setitle8);
        search_setitle8.setBounds(220, 200, 310, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/zali.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 240, 130, 120);

        search_setitle9.setFont(new java.awt.Font("MRT_Naskhi", 3, 24)); // NOI18N
        search_setitle9.setForeground(new java.awt.Color(255, 255, 0));
        search_setitle9.setText("Name        : Ali Hassan");
        jPanel1.add(search_setitle9);
        search_setitle9.setBounds(220, 270, 280, 40);

        search_setitle4.setFont(new java.awt.Font("MRT_Naskhi", 3, 24)); // NOI18N
        search_setitle4.setForeground(new java.awt.Color(255, 255, 0));
        search_setitle4.setText("Reg No.# : FA17-BSE-032");
        jPanel1.add(search_setitle4);
        search_setitle4.setBounds(220, 310, 310, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/zzuzair.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 370, 130, 120);

        search_setitle10.setFont(new java.awt.Font("MRT_Naskhi", 3, 24)); // NOI18N
        search_setitle10.setForeground(new java.awt.Color(255, 255, 0));
        search_setitle10.setText("Name        : M Uzair Khan");
        jPanel1.add(search_setitle10);
        search_setitle10.setBounds(220, 410, 310, 40);

        search_setitle6.setFont(new java.awt.Font("MRT_Naskhi", 3, 24)); // NOI18N
        search_setitle6.setForeground(new java.awt.Color(255, 255, 0));
        search_setitle6.setText("Reg No.# : FA17-BSE-156");
        jPanel1.add(search_setitle6);
        search_setitle6.setBounds(220, 450, 310, 40);

        exit_main2.setBackground(new java.awt.Color(0, 153, 204));
        exit_main2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exit_main2.setForeground(new java.awt.Color(153, 0, 0));
        exit_main2.setText("MAIN MENU");
        exit_main2.setToolTipText("Press the Button to Exit");
        exit_main2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_main2ActionPerformed(evt);
            }
        });
        jPanel1.add(exit_main2);
        exit_main2.setBounds(50, 520, 140, 30);

        exit_main3.setBackground(new java.awt.Color(0, 153, 204));
        exit_main3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exit_main3.setForeground(new java.awt.Color(153, 0, 0));
        exit_main3.setText("Exit");
        exit_main3.setToolTipText("Press the Button to Exit");
        exit_main3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_main3ActionPerformed(evt);
            }
        });
        jPanel1.add(exit_main3);
        exit_main3.setBounds(430, 520, 90, 30);

        Front.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/   (14).jpg"))); // NOI18N
        jPanel1.add(Front);
        Front.setBounds(-40, -430, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_main2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_main2ActionPerformed
        // TODO add your handling code here:
        Hostel_Mng_Sys hms;
        hms=new Hostel_Mng_Sys();
        this.dispose();
        hms.setVisible(true);
        hms.setAlwaysOnTop(true);
        
    }//GEN-LAST:event_exit_main2ActionPerformed

    private void exit_main3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_main3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_main3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membersOfProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new membersOfProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Front;
    private javax.swing.JButton exit_main2;
    private javax.swing.JButton exit_main3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel search_setitle10;
    private javax.swing.JLabel search_setitle11;
    private javax.swing.JLabel search_setitle3;
    private javax.swing.JLabel search_setitle4;
    private javax.swing.JLabel search_setitle6;
    private javax.swing.JLabel search_setitle8;
    private javax.swing.JLabel search_setitle9;
    // End of variables declaration//GEN-END:variables
}
