
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectw;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Admin
 */
public class ShowList extends javax.swing.JFrame {
ArrayList<Member> newmem;
    /**
     * Creates new form ShowList
     */
    public ShowList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Front = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIST OF MEMBER");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("LIST OF HOSTEL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 10, 500, 70);

        jLabel5.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("MEMBER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 80, 260, 60);

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("SHOW LIST");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 140, 220, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("ENTER");
        jButton1.setToolTipText("ENTER TO SHOW LIST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 140, 140, 40);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(25);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 0, 102));
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("LIST");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 690, 360);

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setText("MAIN MENU");
        jButton3.setToolTipText("ENTER TO BACK MAIN MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 560, 140, 30);

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("EXIT");
        jButton2.setToolTipText("ENTER TO EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 560, 90, 30);

        Front.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/   (4).jpg"))); // NOI18N
        jPanel1.add(Front);
        Front.setBounds(-180, 0, 1920, 1014);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        jTextArea1.append("__________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jTextArea1.append("\n|||---ID---||------NAME------||-----F/NAME-----||-----CNIC NO.-----||--DATE OF BIRTH--||---CONTACT NO.---||-----E-MAIL-----||--ROOM NO.--||-MONTHLY FEE-||---------------------------ADRESS----------------------------|||");
        jTextArea1.append("\n|||--------||----------------||----------------||------------------||-----------------||-----------------||----------------||------------||-------------||-HOUSE NO.-||-STREET NO.--||---CITY NAME---||---STATE NAME---|||");
             
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Hostel_Mng_Sys hms;
        hms=new Hostel_Mng_Sys();
        this.dispose();
        hms.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        ( // Reading the object from a file
        final FileInputStream file = new FileInputStream("Record.csv"); final ObjectInputStream in = new ObjectInputStream(file)) {
            newmem = (ArrayList<Member>) in.readObject();
        }catch (FileNotFoundException | EOFException ex) {
            JOptionPane.showMessageDialog(rootPane,"(FileNotFoundException | EOFException ex");
            Logger.getLogger(ShowList.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane,"IOException | ClassNotFoundException ex");
            Logger.getLogger(ShowList.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Method for deserialization of object
        if(newmem==null){
            jTextArea1.append("\n|||              THERE IS NO RECORD THE LIST IS EMPTY                                        THERE IS NO RECORD THE LIST IS EMPTY                            THERE IS NO RECORD THE LIST IS EMPTY                      |||");
            jTextArea1.append("\n__________________________________________________________________________________________________________________________________________________________________________________________________________________________");
            JOptionPane.showMessageDialog(rootPane,"THERE IS NO RECORD THE LIST IS EMPTY");
            Hostel_Mng_Sys hms = new Hostel_Mng_Sys();
            hms.setVisible(true);
            this.dispose();
        }
        else{
            newmem.forEach((Member n) -> {
                jTextArea1.append("\n|||"+n.getId()+"      |"+n.getName()+"      |"+n.getFather_name()+"      |"+n.getCnic()+"      |"+n.getDate_of_birth()+"      |"+n.getContact()+"      |"+n.getE_mail()+"      |"+n.getRoom_num()+"      |"+n.getMonthly_fee()+"      |"+n.getHouse_num()+"      |"+n.getStreet_num()+"      |"+n.getCity()+"      |"+n.getState()+"|||");
                jTextArea1.append("\n|||________||________________||________________||__________________||_________________||_________________||________________||____________||_____________||___________||_____________||_______________||________________|||");
                System.out.println(n);
            });
            jTextArea1.append("\n__________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ShowList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Front;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
