/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculation;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Farriah D
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpenal = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        ml = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        l2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        mpa = new javax.swing.JPanel();
        modifyBtnLabel2 = new javax.swing.JLabel();
        mpm = new javax.swing.JPanel();
        modifyBtnLabel1 = new javax.swing.JLabel();
        mpsub = new javax.swing.JPanel();
        modifyBtnLabel4 = new javax.swing.JLabel();
        mpd = new javax.swing.JPanel();
        modifyBtnLabel3 = new javax.swing.JLabel();
        mpe = new javax.swing.JPanel();
        modifyBtnLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainpenal.setBackground(new java.awt.Color(102, 51, 153));
        mainpenal.setLayout(null);

        Header.setBackground(new java.awt.Color(140, 20, 252));

        ml.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        ml.setForeground(new java.awt.Color(51, 51, 0));
        ml.setText("SIMPLE  CALCULATOR");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ml, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(ml, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpenal.add(Header);
        Header.setBounds(0, 0, 560, 100);

        l1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("1st num");
        l1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mainpenal.add(l1);
        l1.setBounds(140, 160, 110, 30);

        t1.setBackground(new java.awt.Color(102, 51, 153));
        t1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(null);
        t1.setCaretColor(new java.awt.Color(255, 255, 255));
        t1.setSelectionColor(new java.awt.Color(140, 20, 252));
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        mainpenal.add(t1);
        t1.setBounds(350, 140, 140, 40);
        mainpenal.add(jSeparator2);
        jSeparator2.setBounds(350, 180, 140, 20);

        l2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("2nd num");
        l2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mainpenal.add(l2);
        l2.setBounds(140, 240, 110, 30);

        t2.setBackground(new java.awt.Color(102, 51, 153));
        t2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setBorder(null);
        t2.setCaretColor(new java.awt.Color(255, 255, 255));
        t2.setSelectionColor(new java.awt.Color(140, 20, 252));
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });
        mainpenal.add(t2);
        t2.setBounds(350, 230, 140, 40);
        mainpenal.add(jSeparator4);
        jSeparator4.setBounds(350, 270, 140, 20);

        mpa.setBackground(new java.awt.Color(102, 51, 153));
        mpa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mpa.setToolTipText("click to Modify");
        mpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpaMouseClicked(evt);
            }
        });

        modifyBtnLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        modifyBtnLabel2.setForeground(new java.awt.Color(255, 255, 255));
        modifyBtnLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyBtnLabel2.setText("+");

        javax.swing.GroupLayout mpaLayout = new javax.swing.GroupLayout(mpa);
        mpa.setLayout(mpaLayout);
        mpaLayout.setHorizontalGroup(
            mpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mpaLayout.setVerticalGroup(
            mpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpaLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel2))
        );

        mainpenal.add(mpa);
        mpa.setBounds(160, 310, 80, 40);

        mpm.setBackground(new java.awt.Color(102, 51, 153));
        mpm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mpm.setToolTipText("click to Modify");
        mpm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mpm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpmMouseClicked(evt);
            }
        });

        modifyBtnLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        modifyBtnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        modifyBtnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyBtnLabel1.setText("X");

        javax.swing.GroupLayout mpmLayout = new javax.swing.GroupLayout(mpm);
        mpm.setLayout(mpmLayout);
        mpmLayout.setHorizontalGroup(
            mpmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mpmLayout.createSequentialGroup()
                .addComponent(modifyBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        mpmLayout.setVerticalGroup(
            mpmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpmLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpenal.add(mpm);
        mpm.setBounds(240, 360, 80, 40);

        mpsub.setBackground(new java.awt.Color(102, 51, 153));
        mpsub.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mpsub.setToolTipText("click to Modify");
        mpsub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mpsub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpsubMouseClicked(evt);
            }
        });
        mpsub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mpsubKeyTyped(evt);
            }
        });

        modifyBtnLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        modifyBtnLabel4.setForeground(new java.awt.Color(255, 255, 255));
        modifyBtnLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyBtnLabel4.setText("-");

        javax.swing.GroupLayout mpsubLayout = new javax.swing.GroupLayout(mpsub);
        mpsub.setLayout(mpsubLayout);
        mpsubLayout.setHorizontalGroup(
            mpsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpsubLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mpsubLayout.setVerticalGroup(
            mpsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpsubLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpenal.add(mpsub);
        mpsub.setBounds(80, 360, 80, 40);

        mpd.setBackground(new java.awt.Color(102, 51, 153));
        mpd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mpd.setToolTipText("click to Modify");
        mpd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mpd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpdMouseClicked(evt);
            }
        });

        modifyBtnLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        modifyBtnLabel3.setForeground(new java.awt.Color(255, 255, 255));
        modifyBtnLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyBtnLabel3.setText("/");

        javax.swing.GroupLayout mpdLayout = new javax.swing.GroupLayout(mpd);
        mpd.setLayout(mpdLayout);
        mpdLayout.setHorizontalGroup(
            mpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mpdLayout.createSequentialGroup()
                .addComponent(modifyBtnLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        mpdLayout.setVerticalGroup(
            mpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpdLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpenal.add(mpd);
        mpd.setBounds(160, 410, 80, 40);

        mpe.setBackground(new java.awt.Color(102, 51, 153));
        mpe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mpe.setToolTipText("click to Modify");
        mpe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mpe.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mpeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        mpe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpeMouseClicked(evt);
            }
        });

        modifyBtnLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        modifyBtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        modifyBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyBtnLabel.setText("EXIT");

        javax.swing.GroupLayout mpeLayout = new javax.swing.GroupLayout(mpe);
        mpe.setLayout(mpeLayout);
        mpeLayout.setHorizontalGroup(
            mpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mpeLayout.setVerticalGroup(
            mpeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpeLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(modifyBtnLabel))
        );

        mainpenal.add(mpe);
        mpe.setBounds(370, 400, 130, 40);

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Umaid Khan");
        mainpenal.add(jLabel2);
        jLabel2.setBounds(20, 480, 210, 60);

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("FA17-EPE-035");
        mainpenal.add(jLabel1);
        jLabel1.setBounds(300, 480, 240, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpenal, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpenal, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpeMouseClicked
      System.exit(0);
    }//GEN-LAST:event_mpeMouseClicked

    private void mpmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpmMouseClicked
        Integer fst=Integer.parseInt(t1.getText());
        Integer snd=Integer.parseInt(t2.getText());
        JOptionPane.showMessageDialog(rootPane, fst*snd);
        
    }//GEN-LAST:event_mpmMouseClicked

    private void mpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpaMouseClicked
        // TODO add your handling code here:
        Integer fst=Integer.parseInt(t1.getText());
        Integer snd=Integer.parseInt(t2.getText());
        JOptionPane.showMessageDialog(rootPane, fst+snd);
        
        
    }//GEN-LAST:event_mpaMouseClicked

    private void mpdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpdMouseClicked
        // TODO add your handling code here:
        Integer fst=Integer.parseInt(t1.getText());
        Integer snd=Integer.parseInt(t2.getText());
        if(snd!=0){
            if(fst/snd>=1){
                JOptionPane.showMessageDialog(rootPane, fst/snd);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "The Second number is \nmust be gratter then First");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "The Second number is must be non zero");
        }
        
    }//GEN-LAST:event_mpdMouseClicked

    private void mpsubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpsubMouseClicked
        // TODO add your handling code here:
        Integer fst=Integer.parseInt(t1.getText());
        Integer snd=Integer.parseInt(t2.getText());
        JOptionPane.showMessageDialog(rootPane, fst-snd);
        
    }//GEN-LAST:event_mpsubMouseClicked

    private void mpeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mpeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mpeAncestorAdded

    private void mpsubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpsubKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mpsubKeyTyped

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        String str=t1.getText();
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(str.length()>=8))
        {
            evt.consume();
        }
    }//GEN-LAST:event_t1KeyTyped

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
        String str=t2.getText();
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(str.length()>=8))
        {
            evt.consume();
        }
    }//GEN-LAST:event_t2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JPanel mainpenal;
    private javax.swing.JLabel ml;
    private javax.swing.JLabel modifyBtnLabel;
    private javax.swing.JLabel modifyBtnLabel1;
    private javax.swing.JLabel modifyBtnLabel2;
    private javax.swing.JLabel modifyBtnLabel3;
    private javax.swing.JLabel modifyBtnLabel4;
    private javax.swing.JPanel mpa;
    private javax.swing.JPanel mpd;
    private javax.swing.JPanel mpe;
    private javax.swing.JPanel mpm;
    private javax.swing.JPanel mpsub;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
