/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectw;

import java.awt.event.KeyEvent;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.ConcurrentModificationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class delete extends javax.swing.JFrame {
ArrayList <Member> newmem;
    /**
     * Creates new form Search_mem
     */
    public delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnl_search = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        search_memidlbl = new javax.swing.JLabel();
        id_searchtxt = new javax.swing.JTextField();
        serch_namelbl = new javax.swing.JLabel();
        f_name_serchhtxt = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Front2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DELETE MEMBER RECORD");
        setResizable(false);

        pnl_search.setLayout(null);

        jLabel7.setFont(new java.awt.Font("MRT_Naskhi", 3, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("DELETE");
        pnl_search.add(jLabel7);
        jLabel7.setBounds(50, 30, 220, 50);

        jLabel6.setFont(new java.awt.Font("MRT_Naskhi", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("MEMBER RECORD");
        pnl_search.add(jLabel6);
        jLabel6.setBounds(110, 80, 490, 50);

        search_memidlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search_memidlbl.setForeground(new java.awt.Color(153, 255, 51));
        search_memidlbl.setText("Member ID");
        pnl_search.add(search_memidlbl);
        search_memidlbl.setBounds(50, 170, 100, 30);

        id_searchtxt.setBackground(new java.awt.Color(204, 255, 255));
        id_searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_searchtxtKeyTyped(evt);
            }
        });
        pnl_search.add(id_searchtxt);
        id_searchtxt.setBounds(190, 170, 160, 30);
        id_searchtxt.getAccessibleContext().setAccessibleName("search id");
        id_searchtxt.getAccessibleContext().setAccessibleDescription("Enter ID of Member");

        serch_namelbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        serch_namelbl.setForeground(new java.awt.Color(255, 200, 0));
        serch_namelbl.setText("Name");
        pnl_search.add(serch_namelbl);
        serch_namelbl.setBounds(50, 230, 80, 20);

        f_name_serchhtxt.setBackground(new java.awt.Color(204, 255, 255));
        f_name_serchhtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f_name_serchhtxtKeyTyped(evt);
            }
        });
        pnl_search.add(f_name_serchhtxt);
        f_name_serchhtxt.setBounds(190, 220, 160, 30);

        jButton10.setBackground(new java.awt.Color(0, 153, 204));
        jButton10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 0, 0));
        jButton10.setText("DELETE");
        jButton10.setToolTipText("ENTER TO BACK MAIN MENU");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pnl_search.add(jButton10);
        jButton10.setBounds(490, 210, 110, 30);

        jTextArea1.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        pnl_search.add(jScrollPane1);
        jScrollPane1.setBounds(50, 260, 550, 240);

        jButton9.setBackground(new java.awt.Color(0, 153, 204));
        jButton9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 0, 0));
        jButton9.setText("MAIN MENU");
        jButton9.setToolTipText("ENTER TO BACK MAIN MENU");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pnl_search.add(jButton9);
        jButton9.setBounds(50, 510, 140, 30);

        jButton11.setBackground(new java.awt.Color(0, 153, 204));
        jButton11.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(153, 0, 0));
        jButton11.setText("EXIT");
        jButton11.setToolTipText("ENTER TO BACK MAIN MENU");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        pnl_search.add(jButton11);
        jButton11.setBounds(520, 510, 80, 30);

        Front2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/Awesome-media-gamescenes.jpg"))); // NOI18N
        pnl_search.add(Front2);
        Front2.setBounds(-970, -450, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_search, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_search, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        System.exit(0);
    }                                         

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Hostel_Mng_Sys hms;
        hms=new Hostel_Mng_Sys();
        this.dispose();
        hms.setVisible(true);
        hms.setAlwaysOnTop(true);
    }                                        

    @SuppressWarnings("unchecked")
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String n = id_searchtxt.getText();
        String ad = f_name_serchhtxt.getText();
        try (FileInputStream file = new FileInputStream("Record.java"); ObjectInputStream in = new ObjectInputStream(file)) {
            newmem= (ArrayList<Member>) in.readObject();
            int k=0;
            int i=-1;
            FileOutputStream fos=new FileOutputStream("Record.java");
            ObjectOutputStream oos=new ObjectOutputStream(fos);
            for( Member c : newmem){
                i++;
                if(c.getId().equals(n) && c.getName().equals(ad)){
                    k=1;
                    
                    jTextArea1.append("||    ID    ||"+c.getId()+"\n||   NAME  ||"+c.getName()+"\n||  F/Name  ||"+c.getFather_name()+"\n||   CNIC   ||"+c.getCnic()+"\n||  D.O.B   ||"+c.getDate_of_birth()+"\n|| CONTACT  ||"+c.getContact()+"\n||  E-Mail   ||"+c.getE_mail()+"\n||   ROOM   ||"+ (c.getRoom_num()) +"\n||  M.FEE   ||"+ (c.getMonthly_fee()) +"\n||  House   ||"+c.getHouse_num()+"\n||  Street  ||"+c.getStreet_num()+"\n||   City||:"+c.getCity()+"\n||  StATE   ||"+c.getState());
                    int j=JOptionPane.showConfirmDialog(null,"Do you want to delete?","Delete Conformation",JOptionPane.YES_NO_OPTION);
                    if(j==0){
                        newmem.remove(i);
                        oos.writeObject(newmem);
                        JOptionPane.showMessageDialog(rootPane,"REMOVING DONE! ");
                    }
                    oos.close();
                    fos.close();
                    file.close();
                    in.close();
                }
            }
            if(k!=1){
                 JOptionPane.showMessageDialog(rootPane,"NOT FOUND");
            }
        }catch(ConcurrentModificationException h){
        } catch (FileNotFoundException | EOFException ex) {
            Logger.getLogger(delete.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(delete.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }                                         

    private void id_searchtxtKeyTyped(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        String str=id_searchtxt.getText();
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(str.length()>=6))
        {
            evt.consume();
        }
    }                                     

    private void f_name_serchhtxtKeyTyped(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
        String str=f_name_serchhtxt.getText();
        char c=evt.getKeyChar();
        if((Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(str.length()>=20)){
            evt.consume();
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Front2;
    private javax.swing.JTextField f_name_serchhtxt;
    private javax.swing.JTextField id_searchtxt;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnl_search;
    private javax.swing.JLabel search_memidlbl;
    private javax.swing.JLabel serch_namelbl;
    // End of variables declaration                   
}
