/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectw;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class Hostel_Mng_Sys extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Hostel_Mng_Sys() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addmem1 = new javax.swing.JButton();
        searchMem2 = new javax.swing.JButton();
        removeMem1 = new javax.swing.JButton();
        showList1 = new javax.swing.JButton();
        editMem1 = new javax.swing.JButton();
        searchMem1 = new javax.swing.JButton();
        exit_main1 = new javax.swing.JButton();
        searchMem3 = new javax.swing.JButton();
        exit_main2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN MENU");
        setBackground(new java.awt.Color(0, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setName("main_frame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        panel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("MRT_Naskhi", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("WELCOME TO ");
        panel2.add(jLabel6);
        jLabel6.setBounds(0, 40, 290, 54);

        jLabel5.setFont(new java.awt.Font("MRT_Naskhi", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("HOSTEL MANAGMENT ");
        panel2.add(jLabel5);
        jLabel5.setBounds(210, 90, 450, 54);

        addmem1.setBackground(new java.awt.Color(0, 153, 204));
        addmem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addmem1.setForeground(new java.awt.Color(153, 0, 0));
        addmem1.setText("Add Member");
        addmem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmem1ActionPerformed(evt);
            }
        });
        panel2.add(addmem1);
        addmem1.setBounds(40, 180, 210, 30);

        searchMem2.setBackground(new java.awt.Color(0, 153, 204));
        searchMem2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchMem2.setForeground(new java.awt.Color(153, 0, 0));
        searchMem2.setText("Search Member");
        searchMem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMem2ActionPerformed(evt);
            }
        });
        panel2.add(searchMem2);
        searchMem2.setBounds(60, 230, 210, 30);

        removeMem1.setBackground(new java.awt.Color(0, 153, 204));
        removeMem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        removeMem1.setForeground(new java.awt.Color(153, 0, 0));
        removeMem1.setText("Delete Member");
        removeMem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMem1ActionPerformed(evt);
            }
        });
        panel2.add(removeMem1);
        removeMem1.setBounds(90, 280, 210, 30);

        showList1.setBackground(new java.awt.Color(0, 153, 204));
        showList1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        showList1.setForeground(new java.awt.Color(153, 0, 0));
        showList1.setText("Show List");
        showList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showList1ActionPerformed(evt);
            }
        });
        panel2.add(showList1);
        showList1.setBounds(130, 330, 210, 30);

        editMem1.setBackground(new java.awt.Color(0, 153, 204));
        editMem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        editMem1.setForeground(new java.awt.Color(153, 0, 0));
        editMem1.setText("Edit Member");
        editMem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMem1ActionPerformed(evt);
            }
        });
        panel2.add(editMem1);
        editMem1.setBounds(180, 380, 210, 30);

        searchMem1.setBackground(new java.awt.Color(0, 153, 204));
        searchMem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchMem1.setForeground(new java.awt.Color(153, 0, 0));
        searchMem1.setText("Insert New USER");
        searchMem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMem1ActionPerformed(evt);
            }
        });
        panel2.add(searchMem1);
        searchMem1.setBounds(470, 430, 150, 30);

        exit_main1.setBackground(new java.awt.Color(0, 153, 204));
        exit_main1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exit_main1.setForeground(new java.awt.Color(153, 0, 0));
        exit_main1.setText("SIGN OUT");
        exit_main1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_main1ActionPerformed(evt);
            }
        });
        panel2.add(exit_main1);
        exit_main1.setBounds(40, 480, 120, 31);

        searchMem3.setBackground(new java.awt.Color(0, 153, 204));
        searchMem3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchMem3.setForeground(new java.awt.Color(153, 0, 0));
        searchMem3.setText("GROUP MEMBERS");
        searchMem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMem3ActionPerformed(evt);
            }
        });
        panel2.add(searchMem3);
        searchMem3.setBounds(240, 430, 210, 30);

        exit_main2.setBackground(new java.awt.Color(0, 153, 204));
        exit_main2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exit_main2.setForeground(new java.awt.Color(153, 0, 0));
        exit_main2.setText("EXIT");
        exit_main2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_main2ActionPerformed(evt);
            }
        });
        panel2.add(exit_main2);
        exit_main2.setBounds(530, 480, 90, 31);

        jLabel7.setFont(new java.awt.Font("MRT_Naskhi", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("SYSTEM");
        panel2.add(jLabel7);
        jLabel7.setBounds(340, 140, 180, 54);

        jLabel8.setFont(new java.awt.Font("MRT_Naskhi", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("CLASS : BSE-3A");
        panel2.add(jLabel8);
        jLabel8.setBounds(200, 490, 290, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/Awesome-media-gamescenes.jpg"))); // NOI18N
        panel2.add(jLabel3);
        jLabel3.setBounds(-630, -10, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void addmem1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Add_new_mem admem;
        
        admem=new Add_new_mem();
        this.dispose();
        admem.setVisible(true);
        
        
    }                                       

    private void searchMem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        SearchMem s_mem;
        s_mem=new SearchMem();
        this.dispose();
        s_mem.setVisible(true);
        
    }                                          

    private void removeMem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        delete dl;
        dl=new delete();
        this.dispose();
        dl.setVisible(true);
        
    }                                          

    private void showList1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ShowList sl;
        sl=new ShowList();
        this.dispose();
        sl.setVisible(true);
        
    }                                         

    private void editMem1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        EditMem em;
        em=new EditMem();
        this.dispose();
        
        em.setVisible(true);
        
    }                                        

    private void searchMem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        SetUserName mem;
        mem=new SetUserName();
        this.dispose();
        mem.setVisible(true);
       
        
    }                                          

    private void exit_main1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Login mem;
        try {
            mem=new Login();
            this.dispose();
            mem.setVisible(true);
            mem.setAlwaysOnTop(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hostel_Mng_Sys.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                          

    private void searchMem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        membersOfProject mem;
        mem=new membersOfProject();
        this.dispose();
        mem.setVisible(true);
        
    }                                          

    private void exit_main2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        System.exit(0);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hostel_Mng_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hostel_Mng_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hostel_Mng_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hostel_Mng_Sys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Hostel_Mng_Sys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addmem1;
    private javax.swing.JButton editMem1;
    private javax.swing.JButton exit_main1;
    private javax.swing.JButton exit_main2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel2;
    private javax.swing.JButton removeMem1;
    private javax.swing.JButton searchMem1;
    private javax.swing.JButton searchMem2;
    private javax.swing.JButton searchMem3;
    private javax.swing.JButton showList1;
    // End of variables declaration                   
}
