/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectw;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    FileReader file1;
    File file = new File("data.java");
    Hostel_Mng_Sys obj=new Hostel_Mng_Sys();
    public Login() throws FileNotFoundException {
        this.file1=new FileReader(file);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        user_nm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pas_field = new javax.swing.JPasswordField();
        exit_main = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        exitbtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOG IN INFO");
        setBackground(new java.awt.Color(0, 153, 204));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("MRT_Naskhi", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("LOG IN TO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 30, 230, 54);

        jLabel5.setFont(new java.awt.Font("MRT_Naskhi", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("HOSTEL MANAGMENT ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 80, 450, 54);

        jLabel6.setFont(new java.awt.Font("MRT_Naskhi", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("SYSTEM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 140, 180, 54);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 200, 0));
        jLabel1.setText("UserName");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 210, 115, 32);

        user_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nmActionPerformed(evt);
            }
        });
        jPanel1.add(user_nm);
        user_nm.setBounds(230, 210, 180, 32);
        user_nm.getAccessibleContext().setAccessibleDescription("Enter Your User Name");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 200, 0));
        jLabel2.setText("Pasword");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 280, 115, 28);

        pas_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(pas_field);
        pas_field.setBounds(230, 280, 180, 28);
        pas_field.getAccessibleContext().setAccessibleDescription("Enter your Pasword Here");

        exit_main.setBackground(new java.awt.Color(0, 153, 204));
        exit_main.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exit_main.setForeground(new java.awt.Color(153, 0, 0));
        exit_main.setText("Log In");
        exit_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_mainActionPerformed(evt);
            }
        });
        jPanel1.add(exit_main);
        exit_main.setBounds(260, 340, 120, 40);

        exitbtn.setBackground(new java.awt.Color(0, 153, 204));
        exitbtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(153, 0, 0));
        exitbtn.setText("BACK");
        exitbtn.setToolTipText("ENTER TO BACK MAIN MENU");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn);
        exitbtn.setBounds(110, 440, 100, 30);

        exitbtn1.setBackground(new java.awt.Color(0, 153, 204));
        exitbtn1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exitbtn1.setForeground(new java.awt.Color(153, 0, 0));
        exitbtn1.setText("EXIT");
        exitbtn1.setToolTipText("ENTER TO BACK MAIN MENU");
        exitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn1);
        exitbtn1.setBounds(430, 440, 80, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/Awesome-media-gamescenes.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-1280, -540, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void pas_fieldActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void user_nmActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void exit_mainActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        FileInputStream fileStream;
        String usr=user_nm.getText();
        String  pas = pas_field.getText();
        try {
            fileStream = new FileInputStream(file);
            InputStreamReader input = new InputStreamReader(fileStream); 
            BufferedReader reader = new BufferedReader(input); 
            String line, line1 ; 
            boolean a=false, b =false;
            while((line = reader.readLine()) != null){
                if(line.equals(usr)){
                    a=true;
                }
            }
            while(( line1 = reader.readLine()) != null) {
                if(line1.equals(pas)){
                    b= true;
                }
            }
            if(a==true){
                if(b==true){
                    this.dispose();
                    obj.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Enter Your Password?");
                }
            }
            else{
                
            
                JOptionPane.showMessageDialog(rootPane,"Enter Your: \n        User-Name?\n          Password?");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                         

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Front a;
        a=new Front();
        this.dispose();
        a.setVisible(true);
        a.setAlwaysOnTop(true);
    }                                       

    private void exitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton exit_main;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton exitbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pas_field;
    private javax.swing.JTextField user_nm;
    // End of variables declaration                   
}
