/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectw;

import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SearchMem extends javax.swing.JFrame {
//Member newmem;
    /**
     * Creates new form SearchMem
     */
    public SearchMem() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        search_memidlbl = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        search_memidlbl2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        btn1sr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        s_t1 = new javax.swing.JTextArea();
        btn2mnu = new javax.swing.JButton();
        btnxt = new javax.swing.JButton();
        Front = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEARCH MEMBER RECORD");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("MRT_Naskhi", 3, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("SEARCH");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 40, 240, 50);

        jLabel6.setFont(new java.awt.Font("MRT_Naskhi", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("MEMBER RECORD");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 90, 490, 50);

        search_memidlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search_memidlbl.setForeground(new java.awt.Color(153, 255, 51));
        search_memidlbl.setText("Member ID");
        jPanel1.add(search_memidlbl);
        search_memidlbl.setBounds(50, 180, 100, 30);

        t1.setBackground(new java.awt.Color(204, 255, 255));
        t1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(170, 180, 150, 30);

        search_memidlbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search_memidlbl2.setForeground(new java.awt.Color(153, 255, 51));
        search_memidlbl2.setText("Name");
        jPanel1.add(search_memidlbl2);
        search_memidlbl2.setBounds(50, 220, 70, 30);

        t2.setBackground(new java.awt.Color(204, 255, 255));
        t2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(170, 220, 150, 30);

        btn1sr.setBackground(new java.awt.Color(0, 153, 204));
        btn1sr.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btn1sr.setForeground(new java.awt.Color(153, 0, 0));
        btn1sr.setText("SEARCH");
        btn1sr.setToolTipText("ENTER TO BACK MAIN MENU");
        btn1sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1srActionPerformed(evt);
            }
        });
        jPanel1.add(btn1sr);
        btn1sr.setBounds(490, 230, 110, 30);

        s_t1.setBackground(new java.awt.Color(204, 255, 255));
        s_t1.setColumns(20);
        s_t1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        s_t1.setRows(5);
        s_t1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                s_t1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(s_t1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 270, 550, 240);

        btn2mnu.setBackground(new java.awt.Color(0, 153, 204));
        btn2mnu.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btn2mnu.setForeground(new java.awt.Color(153, 0, 0));
        btn2mnu.setText("MAIN MENU");
        btn2mnu.setToolTipText("ENTER TO BACK MAIN MENU");
        btn2mnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2mnuActionPerformed(evt);
            }
        });
        jPanel1.add(btn2mnu);
        btn2mnu.setBounds(50, 520, 140, 30);

        btnxt.setBackground(new java.awt.Color(0, 153, 204));
        btnxt.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnxt.setForeground(new java.awt.Color(153, 0, 0));
        btnxt.setText("EXIT");
        btnxt.setToolTipText("ENTER TO BACK MAIN MENU");
        btnxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxtActionPerformed(evt);
            }
        });
        jPanel1.add(btnxt);
        btnxt.setBounds(500, 520, 100, 30);

        Front.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/Awesome-media-gamescenes.jpg"))); // NOI18N
        jPanel1.add(Front);
        Front.setBounds(-80, -480, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void s_t1AncestorAdded(javax.swing.event.AncestorEvent evt) {                                   
        // TODO add your handling code here:
               
    }                                  

    private void btnxtActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        System.exit(0);
    }                                     

    private void btn2mnuActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Hostel_Mng_Sys hms;
        hms=new Hostel_Mng_Sys();
        this.dispose();
        hms.setVisible(true);
        hms.setAlwaysOnTop(true);
    }                                       

    private void btn1srActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String a=t1.getText();
        String b=t2.getText();
        ArrayList <Member> mem;
        int k=0;
        FileInputStream file;
        try {
            file = new FileInputStream("Record.java"); 
            try (ObjectInputStream in = new ObjectInputStream(file)) {
                mem= (ArrayList<Member>) in.readObject();
                int i=-1;
                for( Member c : mem){
                    i++;
                    if((c.getId().equals(a)) | (c.getName().equals(b)) ){
                        k=1;
                        s_t1.append("__________________\n|----------------|\n|ID             :|>>"+c.getId()+"\n|________________|\n|NAME          :|>>"+c.getName()+"\n|________________|\n|F-NAME         :|>>"+c.getFather_name()+"\n|________________|\n|CNIC-NO.       :|>>"+c.getCnic()+"\n|________________|\n|D-O-B          :|>>"+c.getDate_of_birth()+"\n|________________|\nCONTACT NO.    :|>>"+c.getContact()+"\n|________________|\nE-MAIL         :|>>"+c.getE_mail()+"\n|________________|\nROOM NO.       :|>>"+c.getRoom_num()+"\n|________________|\nMonthly Fee    :|>>"+c.getMonthly_fee()+"\n|_______________|\nHOUSE NO.      :|>>"+c.getHouse_num()+"\n|________________|\nSTREET No.     :|>>"+c.getStreet_num()+"\n|________________|\n|CITY NAME      :|>>"+c.getCity()+"\n|________________|\n|STATE NAME     :|>>"+c.getState()+"\n|________________|\n|----------------|\n__________________");
                    }
                }
                if(k!=1){
                    s_t1.append("not found");
                }
                in.close();
            }
            file.close(); 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SearchMem.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,"FileNotFoundException");
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(SearchMem.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,"IOException | ClassNotFoundException");
        }                 
    }                                      

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {                            
        // TODO add your handling code here:
        String str=t1.getText();
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(str.length()>=6))
        {
            evt.consume();
        }
    }                           

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {                            
        // TODO add your handling code here:
        String str=t2.getText();
        char c=evt.getKeyChar();
        if((Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(str.length()>=20)){
            evt.consume();
        }
    }                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SearchMem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Front;
    private javax.swing.JButton btn1sr;
    private javax.swing.JButton btn2mnu;
    private javax.swing.JButton btnxt;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea s_t1;
    private javax.swing.JLabel search_memidlbl;
    private javax.swing.JLabel search_memidlbl2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration                   
}
