package projectw;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class SetUserName extends javax.swing.JFrame {

    /**
     * Creates new form SetUserName
     */
    public SetUserName() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        search_memidlbl = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        search_memidlbl2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        search_memidlbl1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPasswordField();
        regbtn = new javax.swing.JButton();
        mnubtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        Front = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTER NEW USER");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("MRT_Naskhi", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("REGISTER NEW");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 30, 420, 50);

        jLabel7.setFont(new java.awt.Font("MRT_Naskhi", 3, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("USER");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 90, 160, 50);

        search_memidlbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search_memidlbl.setForeground(new java.awt.Color(153, 255, 51));
        search_memidlbl.setText("User Name");
        jPanel1.add(search_memidlbl);
        search_memidlbl.setBounds(50, 220, 100, 30);

        t1.setBackground(new java.awt.Color(204, 255, 255));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(240, 220, 180, 30);

        search_memidlbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search_memidlbl2.setForeground(new java.awt.Color(153, 255, 51));
        search_memidlbl2.setText("Password");
        jPanel1.add(search_memidlbl2);
        search_memidlbl2.setBounds(50, 280, 140, 30);

        p1.setBackground(new java.awt.Color(204, 255, 255));
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        jPanel1.add(p1);
        p1.setBounds(240, 280, 180, 28);

        search_memidlbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search_memidlbl1.setForeground(new java.awt.Color(153, 255, 51));
        search_memidlbl1.setText("Confirm Password");
        jPanel1.add(search_memidlbl1);
        search_memidlbl1.setBounds(50, 340, 180, 30);

        p2.setBackground(new java.awt.Color(204, 255, 255));
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel1.add(p2);
        p2.setBounds(240, 340, 180, 28);

        regbtn.setBackground(new java.awt.Color(0, 153, 204));
        regbtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        regbtn.setForeground(new java.awt.Color(153, 0, 0));
        regbtn.setText("REGISTER");
        regbtn.setToolTipText("ENTER TO BACK MAIN MENU");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });
        jPanel1.add(regbtn);
        regbtn.setBounds(240, 410, 140, 30);

        mnubtn.setBackground(new java.awt.Color(0, 153, 204));
        mnubtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        mnubtn.setForeground(new java.awt.Color(153, 0, 0));
        mnubtn.setText("MAIN MENU");
        mnubtn.setToolTipText("ENTER TO BACK MAIN MENU");
        mnubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubtnActionPerformed(evt);
            }
        });
        jPanel1.add(mnubtn);
        mnubtn.setBounds(50, 480, 140, 30);

        exitbtn.setBackground(new java.awt.Color(0, 153, 204));
        exitbtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(153, 0, 0));
        exitbtn.setText("EXIT");
        exitbtn.setToolTipText("ENTER TO BACK MAIN MENU");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn);
        exitbtn.setBounds(450, 480, 80, 30);

        Front.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectw/Awesome-media-gamescenes.jpg"))); // NOI18N
        jPanel1.add(Front);
        Front.setBounds(-600, -30, 1920, 1090);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {                                   

    }                                  

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        File file=new File("data.java");
        file.delete();
            try {
                FileWriter writer = new FileWriter("data.java");
                String user=t1.getText();
                String pas=p1.getText();
                String cpas=p2.getText();
                if(pas.equals(cpas)){
                
                    writer.write(user);
                    writer.write(pas);
                    writer.close();
                    JOptionPane.showMessageDialog(rootPane,"Registered Now");
                    Hostel_Mng_Sys hms;
                    hms=new Hostel_Mng_Sys();
                    this.dispose();
                    hms.setVisible(true);
                    hms.setAlwaysOnTop(true);
                }
                else{
                    writer.close();
                    SetUserName a=new SetUserName();
                    this.dispose();
                    a.setVisible(true);
                    a.setAlwaysOnTop(true);
                    JOptionPane.showConfirmDialog(rootPane, " Not Mach ");
                }
            } catch (IOException ex) {
                Logger.getLogger(SetUserName.class.getName()).log(Level.SEVERE, null, ex);
            }
    }                                      

    private void mnubtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Hostel_Mng_Sys hms;
        hms=new Hostel_Mng_Sys();
        this.dispose();
        hms.setVisible(true);
        hms.setAlwaysOnTop(true);
    }                                      

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        System.exit(0);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetUserName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Front;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mnubtn;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JButton regbtn;
    private javax.swing.JLabel search_memidlbl;
    private javax.swing.JLabel search_memidlbl1;
    private javax.swing.JLabel search_memidlbl2;
    private javax.swing.JTextField t1;
    // End of variables declaration                   
}
